# Generated by Django 3.2.5 on 2021-08-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('CA', 'Canvas Art'), ('S', 'Sculpture'), ('WC', 'Wood craft'), ('MI', 'Musical instrument'), ('H', 'Handicraft'), ('A', 'Antique'), ('S', 'Statue'), ('P', 'Painting'), ('MA', 'Mithila Art')], max_length=2, null=True),
        ),
    ]
