# Generated by Django 3.2.5 on 2021-08-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('canvas', 'Canvas Art'), ('sculpture', 'Sculpture'), ('wood_craft', 'Wood craft'), ('musical', 'Musical instrument'), ('handicraft', 'Handicraft'), ('antique', 'Antique'), ('statue', 'Statue'), ('painting', 'Painting'), ('mithila_art', 'Mithila Art')], max_length=200, null=True),
        ),
    ]
